package com.runestone.expeval.grammar.parser;

import com.runestone.expeval.operation.AbstractOperation;
import com.runestone.expeval.operation.values.AbstractVariableValueOperation;
import com.runestone.expeval.operation.values.variable.AssignedVariableOperation;

import java.util.Map;

/**
 * Represents the data generated by the {@link LanguageParser} after parsing the expression.
 *
 * @param operation         the root operation of the expression
 * @param variables         the variables used in the expression
 * @param assignedVariables the variables assigned in the expression
 * @author Marcelo Portilho
 */
public record LanguageData(

        AbstractOperation operation,
        Map<String, AbstractVariableValueOperation> variables,
        Map<String, AssignedVariableOperation> assignedVariables

) {
}
