package com.runestone.expeval.api;

public enum IssueCode {
    SYNTAX_ERROR,
    RESULT_TYPE_MISMATCH,
    TYPE_MISMATCH,
    INVALID_CURRENT_ELEMENT,
    INVALID_MEMBER_ACCESS,
    INVALID_MAP_PROPERTY_ACCESS,
    INVALID_METHOD_ARITY,
    INVALID_FUNCTION_ARITY,
    UNKNOWN_PROPERTY,
    UNKNOWN_METHOD,
    UNKNOWN_FUNCTION,
    UNKNOWN_COLLECTION_FUNCTION,
    AMBIGUOUS_METHOD,
    AMBIGUOUS_FUNCTION,
    INCOMPATIBLE_COMPARISON,
    INCOMPATIBLE_IN_OPERANDS,
    INCOMPATIBLE_METHOD_ARGUMENTS,
    INCOMPATIBLE_FUNCTION_ARGUMENTS,
    INCOMPATIBLE_COLLECTION_FUNCTION_ARGUMENTS,
}
