package com.runestone.expeval_mk3.internal.diagnostics;

public enum DiagnosticCode {
    AST_INVALID_DATE_LITERAL,
    AST_INVALID_DATETIME_LITERAL,
    AST_INVALID_TIME_LITERAL,
    PARSE_UNRECOGNIZED_CHARACTER,
    PARSE_UNEXPECTED_TOKEN,
    PARSE_MISSING_TOKEN,
    PARSE_EXTRANEOUS_INPUT,
    PARSE_NO_VIABLE_ALTERNATIVE,
    SEMANTIC_EMPTY_EXPRESSION_FILE,
    SEMANTIC_EXTERNAL_SYMBOL_SHADOWED,
    SEMANTIC_RESERVED_SYMBOL_ASSIGNMENT,
    SEMANTIC_UNRESOLVED_SYMBOL,
    SEMANTIC_CURRENT_ITEM_OUTSIDE_CONTEXT,
    SEMANTIC_CURRENT_ITEM_DEPTH_EXCEEDED,
    SEMANTIC_TYPE_RESTRICTION_CONFLICT,
    SEMANTIC_OPERATOR_TYPE_MISMATCH,
    SEMANTIC_STRICT_UNKNOWN_TYPE_RESTRICTION,
    SEMANTIC_FUNCTION_ARGUMENT_TYPE_MISMATCH,
    SEMANTIC_AMBIGUOUS_FUNCTION_CALL,
    SEMANTIC_INVALID_NUMERIC_CONSTANT
}
