package com.runestone.expeval_mk3.internal.diagnostics;

public enum DiagnosticCode {
    AST_INVALID_DATE_LITERAL,
    AST_INVALID_DATETIME_LITERAL,
    AST_INVALID_TIME_LITERAL,
    PARSE_UNRECOGNIZED_CHARACTER,
    PARSE_UNEXPECTED_TOKEN,
    PARSE_MISSING_TOKEN,
    PARSE_EXTRANEOUS_INPUT,
    PARSE_NO_VIABLE_ALTERNATIVE,
    SEMANTIC_EMPTY_EXPRESSION_FILE,
    SEMANTIC_EXTERNAL_SYMBOL_SHADOWED
}
