package com.runestone.expeval_mk3.internal.diagnostics;

import com.runestone.expeval_mk3.api.DiagnosticCategory;
import com.runestone.expeval_mk3.api.DiagnosticSeverity;

public enum DiagnosticCode {
    PARSE_UNRECOGNIZED_CHARACTER("PARSE_UNRECOGNIZED_CHARACTER", DiagnosticCategory.PARSE),
    PARSE_UNEXPECTED_TOKEN("PARSE_UNEXPECTED_TOKEN", DiagnosticCategory.PARSE),
    PARSE_MISSING_TOKEN("PARSE_MISSING_TOKEN", DiagnosticCategory.PARSE),
    PARSE_EXTRANEOUS_INPUT("PARSE_EXTRANEOUS_INPUT", DiagnosticCategory.PARSE),
    PARSE_NO_VIABLE_ALTERNATIVE("PARSE_NO_VIABLE_ALTERNATIVE", DiagnosticCategory.PARSE),
    AST_INVALID_DATE_LITERAL("AST_INVALID_DATE_LITERAL", DiagnosticCategory.SEMANTIC),
    AST_INVALID_DATE_TIME_LITERAL("AST_INVALID_DATE_TIME_LITERAL", DiagnosticCategory.SEMANTIC),
    SEMANTIC_EMPTY_EXPRESSION("SEMANTIC_EMPTY_EXPRESSION", DiagnosticCategory.SEMANTIC),
    SEMANTIC_EMPTY_COLLECTION_REQUIRES_CONTEXT("SEMANTIC_EMPTY_COLLECTION_REQUIRES_CONTEXT", DiagnosticCategory.SEMANTIC),
    SEMANTIC_COLLECTION_ELEMENT_TYPE_MISMATCH("SEMANTIC_COLLECTION_ELEMENT_TYPE_MISMATCH", DiagnosticCategory.SEMANTIC),
    SEMANTIC_EQUALITY_TYPE_MISMATCH("SEMANTIC_EQUALITY_TYPE_MISMATCH", DiagnosticCategory.SEMANTIC),
    SEMANTIC_OBJECT_EQUALITY_NOT_SUPPORTED("SEMANTIC_OBJECT_EQUALITY_NOT_SUPPORTED", DiagnosticCategory.SEMANTIC),
    SEMANTIC_MATERIALIZATION_LIMIT_EXCEEDED("SEMANTIC_MATERIALIZATION_LIMIT_EXCEEDED", DiagnosticCategory.SEMANTIC),
    SEMANTIC_UNKNOWN_SYMBOL("SEMANTIC_UNKNOWN_SYMBOL", DiagnosticCategory.SEMANTIC),
    SEMANTIC_UNKNOWN_FUNCTION("SEMANTIC_UNKNOWN_FUNCTION", DiagnosticCategory.SEMANTIC),
    SEMANTIC_UNKNOWN_MEMBER("SEMANTIC_UNKNOWN_MEMBER", DiagnosticCategory.SEMANTIC),
    SEMANTIC_NAVIGATION_RECEIVER_NOT_SUPPORTED("SEMANTIC_NAVIGATION_RECEIVER_NOT_SUPPORTED", DiagnosticCategory.SEMANTIC),
    SEMANTIC_OPERATION_ARGUMENT_MISMATCH("SEMANTIC_OPERATION_ARGUMENT_MISMATCH", DiagnosticCategory.SEMANTIC),
    SEMANTIC_OPERATOR_TYPE_MISMATCH("SEMANTIC_OPERATOR_TYPE_MISMATCH", DiagnosticCategory.SEMANTIC),
    SEMANTIC_LAMBDA_ARGUMENT_UNSUPPORTED("SEMANTIC_LAMBDA_ARGUMENT_UNSUPPORTED", DiagnosticCategory.SEMANTIC),
    SEMANTIC_CONDITIONAL_TYPE_MISMATCH("SEMANTIC_CONDITIONAL_TYPE_MISMATCH", DiagnosticCategory.SEMANTIC),
    SEMANTIC_ASSIGNMENT_TARGET_MISMATCH("SEMANTIC_ASSIGNMENT_TARGET_MISMATCH", DiagnosticCategory.SEMANTIC),
    SEMANTIC_REGEX_PATTERN_INVALID("SEMANTIC_REGEX_PATTERN_INVALID", DiagnosticCategory.SEMANTIC),
    SEMANTIC_SYMBOL_SHADOWING("SEMANTIC_SYMBOL_SHADOWING", DiagnosticCategory.SEMANTIC, DiagnosticSeverity.WARNING),
    SEMANTIC_DUPLICATE_ASSIGNMENT_TARGET("SEMANTIC_DUPLICATE_ASSIGNMENT_TARGET", DiagnosticCategory.SEMANTIC),
    SEMANTIC_DESTRUCTURING_SIZE_MISMATCH("SEMANTIC_DESTRUCTURING_SIZE_MISMATCH", DiagnosticCategory.SEMANTIC),
    SEMANTIC_CURRENT_ITEM_OUT_OF_SCOPE("SEMANTIC_CURRENT_ITEM_OUT_OF_SCOPE", DiagnosticCategory.SEMANTIC),
    SEMANTIC_CURRENT_ITEM_DEPTH_EXCEEDED("SEMANTIC_CURRENT_ITEM_DEPTH_EXCEEDED", DiagnosticCategory.SEMANTIC),
    SEMANTIC_COLLECTION_INDEX_OUT_OF_BOUNDS("SEMANTIC_COLLECTION_INDEX_OUT_OF_BOUNDS", DiagnosticCategory.SEMANTIC),
    SEMANTIC_NULLABLE_RESULT_NOT_ALLOWED("SEMANTIC_NULLABLE_RESULT_NOT_ALLOWED", DiagnosticCategory.SEMANTIC, SuggestionPolicy.REQUIRED),
    SEMANTIC_NULLABLE_ASSIGNMENT_NOT_ALLOWED("SEMANTIC_NULLABLE_ASSIGNMENT_NOT_ALLOWED", DiagnosticCategory.SEMANTIC, SuggestionPolicy.REQUIRED),
    SEMANTIC_NULLABLE_OPERAND_NOT_ALLOWED("SEMANTIC_NULLABLE_OPERAND_NOT_ALLOWED", DiagnosticCategory.SEMANTIC, SuggestionPolicy.REQUIRED),
    SEMANTIC_NULLABLE_ARGUMENT_NOT_ALLOWED("SEMANTIC_NULLABLE_ARGUMENT_NOT_ALLOWED", DiagnosticCategory.SEMANTIC, SuggestionPolicy.REQUIRED),
    SEMANTIC_NULLABLE_RECEIVER_NOT_ALLOWED("SEMANTIC_NULLABLE_RECEIVER_NOT_ALLOWED", DiagnosticCategory.SEMANTIC, SuggestionPolicy.REQUIRED),
    SEMANTIC_NULLABLE_PREDICATE_NOT_ALLOWED("SEMANTIC_NULLABLE_PREDICATE_NOT_ALLOWED", DiagnosticCategory.SEMANTIC, SuggestionPolicy.REQUIRED),
    SEMANTIC_POWER_COMPLEX_DOMAIN("SEMANTIC_POWER_COMPLEX_DOMAIN", DiagnosticCategory.SEMANTIC),
    SEMANTIC_POWER_UNDEFINED("SEMANTIC_POWER_UNDEFINED", DiagnosticCategory.SEMANTIC),
    SEMANTIC_ROOT_COMPLEX_DOMAIN("SEMANTIC_ROOT_COMPLEX_DOMAIN", DiagnosticCategory.SEMANTIC),
    SEMANTIC_ROOT_UNDEFINED("SEMANTIC_ROOT_UNDEFINED", DiagnosticCategory.SEMANTIC),
    SEMANTIC_FACTORIAL_NOT_INTEGRAL("SEMANTIC_FACTORIAL_NOT_INTEGRAL", DiagnosticCategory.SEMANTIC),
    SEMANTIC_FACTORIAL_NEGATIVE("SEMANTIC_FACTORIAL_NEGATIVE", DiagnosticCategory.SEMANTIC),
    SEMANTIC_FACTORIAL_EXCEEDS_MAXIMUM("SEMANTIC_FACTORIAL_EXCEEDS_MAXIMUM", DiagnosticCategory.SEMANTIC),
    RUNTIME_POWER_COMPLEX_DOMAIN("RUNTIME_POWER_COMPLEX_DOMAIN", DiagnosticCategory.RUNTIME),
    RUNTIME_POWER_UNDEFINED("RUNTIME_POWER_UNDEFINED", DiagnosticCategory.RUNTIME),
    RUNTIME_ROOT_COMPLEX_DOMAIN("RUNTIME_ROOT_COMPLEX_DOMAIN", DiagnosticCategory.RUNTIME),
    RUNTIME_ROOT_UNDEFINED("RUNTIME_ROOT_UNDEFINED", DiagnosticCategory.RUNTIME),
    RUNTIME_FACTORIAL_NOT_INTEGRAL("RUNTIME_FACTORIAL_NOT_INTEGRAL", DiagnosticCategory.RUNTIME),
    RUNTIME_FACTORIAL_NEGATIVE("RUNTIME_FACTORIAL_NEGATIVE", DiagnosticCategory.RUNTIME),
    RUNTIME_FACTORIAL_EXCEEDS_MAXIMUM("RUNTIME_FACTORIAL_EXCEEDS_MAXIMUM", DiagnosticCategory.RUNTIME),
    RUNTIME_DESTRUCTURING_SIZE_TOO_SMALL("RUNTIME_DESTRUCTURING_SIZE_TOO_SMALL", DiagnosticCategory.RUNTIME),
    RUNTIME_SUBSCRIPT_OUT_OF_BOUNDS("RUNTIME_SUBSCRIPT_OUT_OF_BOUNDS", DiagnosticCategory.RUNTIME),
    RUNTIME_MAP_KEY_NOT_FOUND("RUNTIME_MAP_KEY_NOT_FOUND", DiagnosticCategory.RUNTIME),
    RUNTIME_MEMBER_ACCESS_FAILURE("RUNTIME_MEMBER_ACCESS_FAILURE", DiagnosticCategory.RUNTIME),
    RUNTIME_INVALID_OPERATION_ARGUMENT("RUNTIME_INVALID_OPERATION_ARGUMENT", DiagnosticCategory.RUNTIME),
    RUNTIME_MATERIALIZATION_LIMIT_EXCEEDED("RUNTIME_MATERIALIZATION_LIMIT_EXCEEDED",
            DiagnosticCategory.RUNTIME, DiagnosticSeverity.ERROR, SourceSpanPolicy.OPTIONAL, SuggestionPolicy.FORBIDDEN),
    RUNTIME_INVALID_EXTERNAL_INPUT("RUNTIME_INVALID_EXTERNAL_INPUT",
            DiagnosticCategory.RUNTIME, DiagnosticSeverity.ERROR, SourceSpanPolicy.FORBIDDEN, SuggestionPolicy.FORBIDDEN),
    RUNTIME_UNDEFINED_OPERATION("RUNTIME_UNDEFINED_OPERATION", DiagnosticCategory.RUNTIME),
    RUNTIME_CALCULATION_FAILURE("RUNTIME_CALCULATION_FAILURE", DiagnosticCategory.RUNTIME),
    RUNTIME_PROVIDER_FAILURE("RUNTIME_PROVIDER_FAILURE", DiagnosticCategory.RUNTIME),
    RUNTIME_RETURN_NULL("RUNTIME_RETURN_NULL", DiagnosticCategory.RUNTIME),
    RUNTIME_RETURN_TYPE_MISMATCH("RUNTIME_RETURN_TYPE_MISMATCH", DiagnosticCategory.RUNTIME),
    RUNTIME_RETURN_INVALID_CONTAINER("RUNTIME_RETURN_INVALID_CONTAINER", DiagnosticCategory.RUNTIME),
    RUNTIME_FORBIDDEN_NULL("RUNTIME_FORBIDDEN_NULL",
            DiagnosticCategory.RUNTIME, DiagnosticSeverity.ERROR, SourceSpanPolicy.OPTIONAL, SuggestionPolicy.FORBIDDEN);

    private final String code;
    private final DiagnosticCategory category;
    private final DiagnosticSeverity severity;
    private final SourceSpanPolicy sourceSpanPolicy;
    private final SuggestionPolicy suggestionPolicy;

    DiagnosticCode(String code, DiagnosticCategory category) {
        this(code, category, DiagnosticSeverity.ERROR, SourceSpanPolicy.REQUIRED, SuggestionPolicy.FORBIDDEN);
    }

    DiagnosticCode(String code, DiagnosticCategory category, DiagnosticSeverity severity) {
        this(code, category, severity, SourceSpanPolicy.REQUIRED, SuggestionPolicy.FORBIDDEN);
    }

    DiagnosticCode(String code, DiagnosticCategory category, SuggestionPolicy suggestionPolicy) {
        this(code, category, DiagnosticSeverity.ERROR, SourceSpanPolicy.REQUIRED, suggestionPolicy);
    }

    DiagnosticCode(
            String code,
            DiagnosticCategory category,
            DiagnosticSeverity severity,
            SourceSpanPolicy sourceSpanPolicy,
            SuggestionPolicy suggestionPolicy) {
        this.code = code;
        this.category = category;
        this.severity = severity;
        this.sourceSpanPolicy = sourceSpanPolicy;
        this.suggestionPolicy = suggestionPolicy;
    }

    public String code() {
        return code;
    }

    DiagnosticCategory category() {
        return category;
    }

    DiagnosticSeverity severity() {
        return severity;
    }

    SourceSpanPolicy sourceSpanPolicy() {
        return sourceSpanPolicy;
    }

    SuggestionPolicy suggestionPolicy() {
        return suggestionPolicy;
    }
}
